services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - webnet
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - webnet
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: wordpress
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - webnet
    restart: always

volumes:
  wordpress-data:
  mariadb-data:

networks:
  webnet:
    driver: bridge
