services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - volume_db:/var/lib/mysql
    networks:
      - webnet
    secrets:
      - db_root_password
      - db_password
      - credentials
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - volume_wp:/var/www/html
    networks:
      - webnet
    secrets:
      - db_root_password
      - db_password
      - credentials
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    container_name: nginx
    volumes:
      - volume_wp:/var/www/html
    networks:
      - webnet
    secrets:
      - credentials
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
      - wordpress

networks:
  webnet:
    driver: bridge


volumes:
  volume_wp:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  volume_db:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind


secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
