services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - volume_db:/var/lib/mysql
    networks:
      - webnet
    env_file:
      - .env
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - volume_wp:/var/www/html
    networks:
      - webnet
    env_file:
      - .env
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    container_name: nginx
    volumes:
      - volume_wp:/var/www/html
    networks:
      - webnet
    env_file:
      - .env
    depends_on:
      - mariadb
      - wordpress

networks:
  webnet:
    driver: bridge


volumes:
  volume_wp:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  volume_db:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind
