services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - /home/${USER}/data/mariadb:/var/lib/mysql
    networks:
      - webnet
    env_file:
      - .env
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/${USER}/data/wordpress:/var/www/html
    networks:
      - webnet
    env_file:
      - .env
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    container_name: nginx
    volumes:
      - /home/${USER}/data/wordpress:/var/www/html
    networks:
      - webnet
    env_file:
      - .env
    depends_on:
      - wordpress

networks:
  webnet:
    driver: bridge

volumes:
  mariadb:
  wordpress:
